- name: Install Git and Docker, clone repository, and bring up portfolio website docker compose
  hosts: aws
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install Git
      apt:
        name: git
        state: present
      become: yes

    - name: Install prerequisites for Docker
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
      become: yes

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: yes

    - name: Set up the stable repository for Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_version }} stable
        state: present
      become: yes

    - name: Install Docker engine
      apt:
        name: docker-ce
        state: present
        update_cache: yes
      become: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
      become: yes

    - name: Ensure Docker service is started
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Clone the GitHub repository
      git:
        repo: "{{ git_repo }}"
        dest: "/home/ubuntu/portfolio-website"
      become: yes
      become_user: "{{ username }}"

    - name: Copy certificate to remote host
      copy:
        src: "{{ certificate_path }}.crt"
        dest: "/home/ubuntu/portfolio-website/config/ssl"
      become: yes

    - name: Copy key to remote host
      copy:
        src: "{{ certificate_path }}.key"
        dest: "/home/ubuntu/portfolio-website/config/ssl"
      become: yes

    - name: Run docker-compose build
      command: docker-compose build
      args:
        chdir: /home/ubuntu/portfolio-website
      become: yes

    - name: Run docker-compose up
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu/portfolio-website
      become: yes